### ISSUE TITLE
Copy external dlls to final module directory

### ISSUE THREAD

**Issue by MartinPerry** [wjakob/nanobind_example#10]
After the nanobind_example is build, I want to copy some external dlls to the final destination folder. However, 

```
add_custom_command(TARGET nanobind_example_ext POST_BUILD 
               COMMAND ${CMAKE_COMMAND} -E copy
               "D:/my_folder/some_lib.dll"              
                $<TARGET_FILE_DIR:nanobind_example_ext>)	
```

is not working. How to fix this?

**Comment by wjakob** [comment]
Not sure -- sorry, this isn't an issue with this repository so I will close the ticket.
