### ISSUE TITLE
Request: A Bazel branch for `nanobind_bazel` tests

### ISSUE THREAD

**Issue by nicholasjng** [wjakob/nanobind_example#40]
I'm currently trying to set up CI for `nanobind_bazel`, and I want to use this example as a build test.

Would it be OK for you to push a `with-bazel` branch (or similar) that contains the setup for a `nanobind_bazel` build of this example, which I can then use in `actions/checkout`? (If not, I can also fork of course.)

**Comment by wjakob** [comment]
Certainly. I will add you as a committer, feel free to make branches as you please.

**Comment by wjakob** [comment]
Naming-wise, I think I have a preference for just `bazel` instead of `with-bazel`.

**Comment by nicholasjng** [comment]
The `bazel` branch is pushed, first [tests](https://github.com/nicholasjng/nanobind-bazel/actions/runs/7979879928) have passed (but not all of them, ABI mismatches). Thanks!
