### ISSUE TITLE
Linking against shared library

### ISSUE THREAD

**Issue by ianhbell** [wjakob/nanobind_example#45]
Perhaps this is out of scope for this "hello world " nanobind repo, but a use case I am struggling with that is not that unconventional is that I have an external library (GEOS in this case) that I HAVE to link against dynamically due its license (LGPL v 2.1). When I was linking statically everything was peachy but now I'm in DLL hell with editable installation (which is key for quick development).  The ``@rpath`` doesn't seem to be getting set properly and it is not entirely clear to me how I should be handling this. I've tried a number of incantations of CMAKE rpath messing about but so far I still can't load both my nanobind main repo and the dependent library.

**Comment by wjakob** [comment]
These things are just hard, period. But they aren't really related to nanobind. I will close the ticket because I lack the time to provide this level of support. If you wish to contribute documentation yourself, then feel free to open a PR.

**Comment by ianhbell** [comment]
Fair enough
