### ISSUE TITLE
PR with single-sourcing version from pyproject.toml?

### ISSUE THREAD

**Issue by ianhbell** [wjakob/nanobind_example#46]
Are you interested in a PR that adds single-sourcing the version and creates a ``__version__`` attribute in the compiled extension to mirror other libraries like numpy, scipy, etc.?

**Comment by wjakob** [comment]
I think I prefer this repo to be absolutely tiny. A large/comprehensive base repo with many bells and whistles (e.g. pre-commit) could be interesting, but I don't see this repo as satisfying this role.
