### ISSUE TITLE
Test error in GitHub workflow

### ISSUE THREAD

**Issue by dofuuz** [wjakob/nanobind_example#49]
There is wrong YAML formatting in:
https://github.com/wjakob/nanobind_example/blob/26ff4b253e089d802b446a1cd900e58054036a17/.github/workflows/pip.yml#L33-L34

This runs
```
python -m pip install pytest pip install --verbose .
```
and tries to install `pytest`, `pip`, `install`, `.`.
`install` package is removed from PyPI and [causing error](https://github.com/dofuuz/python-soxr/actions/runs/10121170118/job/27991795530#step:5:2).
https://github.com/pypi/support/issues/451

This should be fixed something like [this](https://github.com/dofuuz/python-soxr/commit/7b1c7f626d9f5558a36bcb991689cd3a57f8eb74):
```
      run: |
        python -m pip install pytest
        pip install --verbose .
```

**Comment by wjakob** [comment]
Fixed, thank you!
